name: Update README

on:
  schedule:
    # At 00:00 every mon,wed,fri
    - cron: '0 0 * * 1,2,3,4,5'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update README
        run: |
          echo "Updated: $(date)" > README.md
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "auto-update"
          git push
